// apps/react-to-do/src/app/app.tsx
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import { TodoApp } from './todo/TodoApp';

const queryClient = new QueryClient();

export function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <main className="min-h-screen bg-gradient-to-br from-blue-50 to-blue-200 flex flex-col items-center justify-center">
        <TodoApp />
      </main>
    </QueryClientProvider>
  );
}

export default App;

// apps/angular-to-do/src/app/app.ts
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { TodoApp } from './ TodoApp';

@Component({
  imports: [RouterModule, TodoApp],
  selector: 'app-root',
  template: `
    <main
      class="min-h-screen bg-gradient-to-br from-blue-50 to-blue-200 flex flex-col items-center justify-center"
    >
      <app-todo-app></app-todo-app>
    </main>
  `,
})
export class App {}
