// apps/react-to-do/src/app/todo/TodoList.tsx
export interface Todo {
  id: string;
  text: string;
  completed: boolean;
}

export interface TodoListProps {
  todos: Todo[];
  onToggle: (id: string) => void;
  onDelete: (id: string) => void;
}

export function TodoList({ todos, onToggle, onDelete }: TodoListProps) {
  return (
    <ul className="space-y-2">
      {todos.map((todo) => (
        <li
          key={todo.id}
          className="flex items-center justify-between bg-white rounded shadow p-3"
        >
          <span
            className={
              'flex-1 text-lg cursor-pointer select-none ' +
              (todo.completed ? 'line-through text-gray-400' : 'text-gray-900')
            }
            onClick={() => onToggle(todo.id)}
          >
            {todo.text}
          </span>
          <button
            className="ml-4 text-red-500 hover:text-red-700"
            onClick={() => onDelete(todo.id)}
            aria-label="Delete"
          >
            &times;
          </button>
        </li>
      ))}
    </ul>
  );
}

// apps/angular-to-do/src/app/todo/TodoList.ts
import { Component, input, output } from '@angular/core';

export interface Todo {
  id: string;
  text: string;
  completed: boolean;
}

@Component({
  selector: 'app-todo-list',
  standalone: true,
  template: `
    <ul class="space-y-2">
      @for (todo of todos(); track todo.id) {
        <li class="flex items-center justify-between bg-white rounded shadow p-3">
          <span
            class="flex-1 text-lg cursor-pointer select-none"
            [class.line-through]="todo.completed"
            [class.text-gray-400]="todo.completed"
            [class.text-gray-900]="!todo.completed"
            tabindex="0"
            role="button"
            (click)="toggleTodo.emit(todo.id)"
            (keyup.enter)="toggleTodo.emit(todo.id)"
          >
            {{ todo.text }}
          </span>
          <button
            class="ml-4 text-red-500 hover:text-red-700"
            (click)="deleteTodo.emit(todo.id)"
            aria-label="Delete"
          >
            &times;
          </button>
        </li>
      }
    </ul>
  `,
})
export class TodoListComponent {
  todos = input.required<Todo[]>();
  toggleTodo = output<string>();
  deleteTodo = output<string>();
}
